name: Bug report
description: Open an issue about a site bug
labels: ["type: bug", "stage: uninspected"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: has-searched-issues
    attributes:
      label: Did you search existing issues yet?
      description: Have you searched the existing issues for something that is similar to your issue?
      options:
        - label: I have searched existing issues and did not find a duplicate of my issue
          required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Something must have went wrong! What did I get wrong?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Select the browser(s) you tested this bug on.
      description: |
        **Keep in mind that my page is developed on a Firefox based browser.**
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything else we should know?
    validations:
      required: false
